export class Texts {
  public Texts = {
    DentalClinic: "Dental Clinic",
    Profile: "Profile",
    Username: "Username",
    Password: "Password",
    UserType: "User Type",
    Locked: "Is Locked",
    Roles: "Roles",
    Employee: "Employee",
    Doctor: "Doctor",
    Save: "Save",
    Cancel: "Cancel",
    UserManagement : "User Management",
    RoleManagement: 'Role Management',
    RoleName: 'Role Name',
    All: 'All',
    Add: 'Add',
    Edit: 'Edit',
    Delete: 'Delete',
    Get: 'Get',
    Visits: 'Visits',
    Users: 'Users',
    Doctors: 'Doctors',
    Employees: 'Employees',
    Expenses: 'Expenses',
    Patients: 'Patients',
    DoctorManagement: 'Doctor Management',
    PatientManagement: "Patient Management",
    Firstname: "Firstname",
    Lastname: "Lastname",
    Male: "Male",
    Female: "Female",
    DateOfBirth: "Date of Birth",
    Mobile: "Mobile",
    Email: "Email",
    Address: "Address",
    Age: "Age",
    DoctorName: "Doctor Name",
    PatientName: "Patient Name",
    PatientMobile: "Patient Mobile",
    Patient: "Patient",
    Room: "Room",
    PreOperationFee: "Pre-operation Fee",
    PostOperationFee: "Post-operation Fee",
    ScheduleDate: "Schedule Date",
    DoneDate: "Done Date",
    OperationType: "Operation Type",
    PriorityLevel: "Priority Level",
    Description: "Description",
    VisitManagement: "Visit Management",
    TakeOut: "TakeOut",
    Fill: "Fill",
    Orthodontics: "Orthodontics",
    Cleaning: "Cleaning",
    Cover: "Cover",
    None: "None",
    Low: "Low",
    Medium: "Medium",
    High: "High",
    Urgent: "Urgent",
    EmployeeManagement: "Employee Management",
    ItemName: "Item Name",
    ExpenseManagement: "Expense Management",
    StartDate: "Start Date",
    EndDate: "End Date",
    PricePerItem: "Price Per Item",
    Count: "Count",
    Date: "Date",
    CantAccessPageError: "Cannot Access Requested Page",
    LoginPage: "Login Page",
    Login: "Login",
    Logout: "Logout",
    Dashboard: "Dashboard",
    English: "English",
    Dari: "Dari",
    Reports: "Reports",
    Live: "Live",
    Photo: "Photo"
  };
}
